### ISSUE TITLE
Alert Script

### ISSUE THREAD

**Issue by Leaper54** [Mason10198/SkywarnPlus#102]
The ETSNJ repeater has two tail messages. One is the SkywarnPlus alert, and the other is called ' tail ', which is a local announcement AND wx-tail from SkywarnPlus. The announcement is called ' tailmess.wav '.
In rpt.conf: tailmessagelist=/tmp/SkywarnPlus/wx-tail,tail, tail. In config.yaml, I have this alertscript: 
**AlertScript:
  Enable: true
  Mappings:
    - Type: BASH
      Commands:
         - '/etc/asterisk/scripts/Skytail.sh'
      ClearCommands:
         - '/etc/asterisk/scripts/Skytail.sh'
      Triggers:
        - '*Warning'
        - '*Watch'
        - '*Advisory'
        - '*Statement'**
_**The skytail.sh script is:**_
**#!/bin/bash
**# SkywarnPlus update tail**

sox /var/lib/asterisk/sounds/tailmess.wav /tmp/SkywarnPlus/wx-tail.wav /var/lib/asterisk/sounds/tail.wav
sleep 2
mail -s "ETS SkyTail" lengriff@optimum.net </dev/null

exit**

This WORKS when a weather alert begins. When the alert is cleared, the SAME script does NOT clear ' tail '. If ' wx-tail.wav ' is silence, then ' tail ' should be silent. Instead, ' tail ' still has the alert. If I then go to terminal, and run the SAME script, it DOED clear ' tail '. I am stumped!

lengriff@optimum.net / WB2HKK

**Comment by Mason10198** [comment]
Attempting to use ClearCommands with wildcard triggers is not recommended and will likely not work correctly. This is notated in the readme.

https://github.com/Mason10198/SkywarnPlus?tab=readme-ov-file#usage-note

**Comment by Leaper54** [comment]
Thanks Mason. I can appreciate all the work you put in to this. It would help if I just READ all the material! Not sure I did this right. How does this look?
AlertScript:
  Enable: true
  Mappings:
    - Type: BASH
      Commands:
         - '/etc/asterisk/scripts/Skytailon.sh'
      InactiveCommands:
         - '/etc/asterisk/scripts/Skytailoff.sh'
      Triggers:
        - '*Warning'
        - '*Watch'
        - '*Advisory'
        - '*Statement'

**Comment by Leaper54** [comment]
PS: the indents are correct, but get removed in the reply
