### ISSUE TITLE
Maybe a bug?

### ISSUE THREAD

**Issue by w8cpt** [Mason10198/SkywarnPlus#105]
ISSUE TEMPLATE
This template is designed to help you report a bug with information required for you to actually be able to receive help. If you choose to ignore this template, do not provide proper files/information with your report, etc., then your issue will be ignored/closed.

**Describe the bug**
I have a clearnode running this and I have only certain weather events check to announce and it's announcing 3 today I do not have checked,  "Air Quailty Alert, Excessive Heat Warning and one other I forgot lol. The clearnode setup wasn't done by me obviously so I'm not sure why it's doing this. I do have 2 counties selected and I know that's OK on my home built Hamviop node but maybe an issue on Clearnode? I have then like this MIC147,MIC099 

**To Reproduce**
1. Just announces warnings I don't have checked when they are alerted

**Expected behavior**
I expect not to hear Excessive Heat Warning etc when I don't have it checked cause I know it's hot outside haha!

**Files**
Please, at *minimum*, paste or attach the following:
I don't know how to do this with the clear node...

**Screenshots**

**Node (please complete the following information):**
 - OS: Clea node on a Pi 2w.

**Comment by Mason10198** [comment]
I will be unable to provide support for this unless you can SSH into the ClearNode and provide at minimum a copy of the file `/usr/local/bin/SkywarnPlus/config.yaml`. This already sounds like a bug/issue with the ClearNode app, and not SkywarnPlus.

**Comment by w8cpt** [comment]
I thought so too and I'll attach what clearnide dude said...I'm pretty sure
I can ssh into it and try to get that let me work on that...thanks!

**Comment by w8cpt** [comment]
OK I'm not sure because I haven't been in the Mobile node I built in a long time but I think I didn't have them alerts on in that node running hamvoip and I just turned it on and started using it and it's saying all 3 on this node too.  I haven't been able to ssh into either node yet but I will tonight or tonorrow and if they are off in the hamvoip node too I'll send you both nodes files you wanted..

**Comment by Mason10198** [comment]
Unable to reproduce this on any standard SkywarnPlus installs. When adding events to the `SayAlertBlockedEvents` list, they are blocked correctly from `SayAlert`. This must be an issue specific to the Clearnode implementation of SkywarnPlus and needs to be reported to Clearnode.

Closing as this is not an issue with SkywarnPlus.
