### ISSUE TITLE
ASL3 Permissions Problems

### ISSUE THREAD

**Issue by Mason10198** [Mason10198/SkywarnPlus#107]
Some permissions issues have been discovered with ASL3 installations - where Asterisk 20 no longer runs as the root user. This problem only exists on ASL3 installations, and does not adversely affect the main `SkywarnPlus.py` script or its operations.

The main `SkywarnPlus.py` script does not have an issue running, because pretty much everyone adds it to the crontab while logged in as root - thus the main script is always executed from roots crontab.

However, the `SkyDescribe.py` and `SkyControl.py` scripts are normally added as functions to rpt.conf, and are thus executed by Asterisk as the asterisk user. The asterisk user does not have permission to access any files owned/created by the root user. This can be seen when manually executing the scripts as the asterisk user:

```
root@ASL3:~# sudo -u asterisk /usr/local/bin/SkywarnPlus/SkyDescribe.py 1
Traceback (most recent call last):
  File "/usr/local/bin/SkywarnPlus/SkyDescribe.py", line 82, in <module>
    FH = logging.FileHandler(LOG_PATH)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/tmp/SkywarnPlus/SkyDescribe.log'
```
```
root@ASL3:~# sudo -u asterisk /usr/local/bin/SkywarnPlus/SkyControl.py enable toggle
Traceback (most recent call last):
  File "/usr/local/bin/SkywarnPlus/SkyControl.py", line 234, in <module>
    with open(str(CONFIG_FILE), "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/SkywarnPlus/config.yaml'
```

Additionally, "installing" SWP as `root` and then simply executing as `asterisk` can cause other issues:
```bash
root@ASL3:~# sudo -u asterisk /usr/local/bin/SkywarnPlus/SkywarnPlus.py
2024-07-16 19:42:03,152 ERROR ChangeCT: Failed to update ct1: [Errno 13] Permission denied: '/usr/local/bin/SkywarnPlus/SOUNDS/TONES/ct1.ulaw'
2024-07-16 19:42:03,153 ERROR ChangeCT: Failed to update ct2: [Errno 13] Permission denied: '/usr/local/bin/SkywarnPlus/SOUNDS/TONES/ct2.ulaw'
An error occurred while writing to /tmp/AUTOSKY: [Errno 13] Permission denied: '/tmp/AUTOSKY/warnings.txt'
An error occurred while writing to /var/www/html/AUTOSKY: [Errno 13] Permission denied: '/var/www/html/AUTOSKY/warnings.txt'
2024-07-16 19:42:04,966 ERROR ChangeCT: Failed to update ct1: [Errno 13] Permission denied: '/usr/local/bin/SkywarnPlus/SOUNDS/TONES/ct1.ulaw'
2024-07-16 19:42:04,967 ERROR ChangeCT: Failed to update ct2: [Errno 13] Permission denied: '/usr/local/bin/SkywarnPlus/SOUNDS/TONES/ct2.ulaw'
```

**Comment by Mason10198** [comment]
I just updated the [official SkywarnPlus installation instructions](https://github.com/Mason10198/SkywarnPlus) for ASL3 compatibility. For users that have already installed SkywarnPlus on their ASL3 node, the "patch" is as follows:

1. **Modify existing crontab entry to execute SkywarnPlus as the `asterisk` user**:
    ```bash
    # Run `crontab -e` and insert 'asterisk' into the line as shown
    * * * * * asterisk /usr/local/bin/SkywarnPlus/SkywarnPlus.py
    ```

2. **Alter permissions**:
    ```bash
    chown -R asterisk:asterisk /usr/local/bin/SkywarnPlus/
    chmod -R u+rwx /usr/local/bin/SkywarnPlus/
    ```

3. **Clear SWP cache**:
    ```bash
    rm -rf /tmp/SkywarnPlus/
    ```

After these quick modifications, there should be no issues executing any of the SWP scripts on ASL3.

**Comment by Mason10198** [comment]
Worth noting that the Supermon/AUTOSKY backwards compatibility (writing alert titles to the now outdated `alerts.txt` for Supermon to display) no longer works, and the feature will be removed in the next release of SkywarnPlus.

```bash
An error occurred while writing to /tmp/AUTOSKY: [Errno 13] Permission denied: '/tmp/AUTOSKY/warnings.txt'
An error occurred while writing to /var/www/html/AUTOSKY: [Errno 13] Permission denied: '/var/www/html/AUTOSKY/warnings.txt'
```

In the future, if data from SkywarnPlus is desired to be displayed or otherwise used in any 3rd party dashboards or softwares, it will be up to those 3rd party dashboards or softwares to implement the required functionality of reading and processing the `data.json` file created and managed by SkywarnPlus.

**Comment by KD5FMU** [comment]
I can see the alerts on Supermon 7.4+ on ASL 3And I like it ;-) just sayin

**Comment by Mason10198** [comment]
That is because you installed SWP the "old" way, where it is is executed via cron as the root user. Supermon display will work when executed as root, but the other issues described at the top of this thread will be present.

**Comment by KD5FMU** [comment]
Thank you for clearing that up for me Mason. And Thank You for SkywarnPlus. You have a made a lot of people Happy with the contribution to Ham and GMRS Radio. 73Fred McGuire, ***@***.*** Jul 17, 2024, at 12:27 AM, Mason ***@***.***> wrote:﻿
That is because you installed SWP the "old" way, where it is is executed via cron as the root user. Supermon display will work when executed as root, but the other issues described at the top of this thread will be present.
