### ISSUE TITLE
Alerts on Supermon page

### ISSUE THREAD

**Issue by rnfuller** [Mason10198/SkywarnPlus#115]
I cannot get the SkyWarnPlus alerts to display on the Supermon Page.

I have reinstalled Supermon7.4+ and have reinstalled SkywarnPlus using the automated script.  I followed all the instruction for ASL3 installs.

SkywarnPlus works beautifully and I hear the alerts, and the changed courtesy tones, but nothing shows up on the Supermon page. 

I see a script in the SkywarnPlus directory named ASL3_Supermon_Workaround.py  If I execute that script as root, the alerts show up in Supermon.  I appears that that script never gets executed when SkyWarnPlus is running.  

I can see in the debug log where it is most likely a permission error, but I am at a loss at how to correct it.

I have attached the log.  I am running the latest version of ASL3

When you get a chance, could you look at the log and advise me what I need to do to correct the permission issues?

Thanks for all your hard work, it is really a great addition to ASL3 and HamVoip!
Randy Fuller N0TRA Allstar Node 468501
rnfuller@gmail.com
[SkywarnPlus.log](https://github.com/user-attachments/files/16825650/SkywarnPlus.log)

**Comment by Mason10198** [comment]
[Read this important note here](https://github.com/Mason10198/SkywarnPlus?tab=readme-ov-file#important-note-about-asl3)

Sounds like you're missing the required crontab entry to run the `ASL3_Supermon_Workaround.py`.

Run this command to add it:
```bash
echo "*/1 * * * * root /usr/local/bin/SkywarnPlus/ASL3_Supermon_Workaround.py" | sudo tee /etc/cron.d/ASL3_Supermon_Workaround > /dev/null
```

Here are the relevant lines of the `swp-install` script that should have handled this when you installed SWP:
```bash
    if [ "$SYSTEM_TYPE" = "ASL3" ]; then
        print_divider
        echo "This is an ASL3 system. In order for Supermon to display SkywarnPlus alerts on ASL3, a second crontab entry needs to be created to run ASL3_Supermon_Workaround.py as the root user."
        
        if [ -d "/var/www/html/supermon/" ]; then
            echo "It looks like you have Supermon installed, so it is recommended to create this crontab entry."
        else
            echo "It looks like you do not have Supermon installed, but you can still safely create this crontab entry in case you decide to use Supermon later."
        fi

        read -r -p "Would you like to create the crontab entry for ASL3_Supermon_Workaround.py now? (Y/n): " CREATE_SUPERMON_CRON
        CREATE_SUPERMON_CRON=${CREATE_SUPERMON_CRON:-y}

        if [[ "$CREATE_SUPERMON_CRON" =~ ^[Yy]$ ]]; then
            SUPERMON_CRON_FILE="/etc/cron.d/ASL3_Supermon_Workaround"
            SUPERMON_CRONTAB_ENTRY="*/$CRONTAB_INTERVAL * * * * root /usr/local/bin/SkywarnPlus/ASL3_Supermon_Workaround.py"
            
            if grep -Fxq "$SUPERMON_CRONTAB_ENTRY" "$SUPERMON_CRON_FILE" 2>/dev/null; then
                echo "Supermon crontab entry already exists. Skipping."
            else
                echo "$SUPERMON_CRONTAB_ENTRY" > "$SUPERMON_CRON_FILE" || {
                    print_divider
                    echo "Failed to create Supermon crontab entry. Exiting."
                    print_divider
                    exit 1
                }
                echo "Supermon crontab entry created successfully."
            fi
        else
            echo "Supermon crontab entry not created."
        fi
    fi
```

**Comment by rnfuller** [comment]
Right after I submitted the issue, I found and entry in the ASL3 log that indicated and error running the script.  I looked in /etc/cron.d and there was and extra character in the cron entry that was causing it to error.  The entry started with */ * * * *, instead of * * * * *
Dont know how the extra character got in there, but i did some cutting and pasting from the instructions to the terminal in ASL3 Cockpit or whatever they call it.  Cutting and pasting in their app does not work well for me.  I much prefer using the plain old terminal and ssh into the box.
At any rate, I corrected the cron entry, and all is well now!

Man, thanks for all the help.  Now I wish someone would port Supermon2 so it would work with ASL3!
I am dropping you a contribution for a great project.  Keep up the good work!

Randy

**Comment by rnfuller** [comment]
Not a bug, it was a typo in an entry.

**Comment by Mason10198** [comment]
This might have been a bug in the installer script since I was using a variable to set the cron interval when it should just always be `*/1` for this particular entry. I have made a small change to the install script to correct this. Thank you for the report and the contribution!
