### ISSUE TITLE
Tailmessage wx-tail.wav

### ISSUE THREAD

**Issue by na7q** [Mason10198/SkywarnPlus#116]
**Is your feature request related to a problem? Please describe.**
Not directly a "problem". Counties should be announced in the tail messages, not just the alert.wav, and they are currently not. 

**Describe the solution you'd like**
Tailmessages should announce the counties that have the alerts. Otherwise the announcements are for unknown counties and no way to know.

**Describe alternatives you've considered**

**Additional context**
If county option is enabled, say the county, otherwise don't.

**Comment by Mason10198** [comment]
Hi Mike, this is already a feature. You just have to enable it in your `config.yaml`.

**Comment by na7q** [comment]
Apparently missed the setting for that! Not a big yaml guy here. So it's a bit more difficult to look over things and get familiar with it.
