### ISSUE TITLE
skywarnPlus shows wrong location of Richboro, PA instead of Almont, MI the code is set to MIC087 showing this in supermon 2 ?

### ISSUE THREAD

**Issue by kb8dvd** [Mason10198/SkywarnPlus#120]
ISSUE TEMPLATE
This template is designed to help you report a bug with information required for you to actually be able to receive help. If you choose to ignore this template, do not provide proper files/information with your report, etc., then your issue will be ignored/closed.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Files**
Please, at *minimum*, paste or attach the following:
- SkywarnPlus Files:
  - `/usr/local/bin/SkywarnPlus/config.yaml`
  - `/tmp/SkywarnPlus/SkywarnPlus.log`
  - `/tmp/SkywarnPlus/data.json`
- Asterisk Files:
  - `/etc/asterisk/rpt.conf`
  - `/var/log/asterisk/messages`

**Screenshots**

**Node (please complete the following information):**
 - OS: [e.g. ASL 1.01, ASL BETA 2.0.0, HAMVOIP 1.7]

**Additional context**
Add any other context about the problem here. This may include `rpt.conf` or other information.

**Comment by Steve-AG2AA** [comment]
your ticket is not very clear. is supermon not showing the correct location
here

![image](https://github.com/user-attachments/assets/dc9bd97c-e0dd-4f74-86a1-5710cf0fa2ed)



or in red when there is a warning?
