### ISSUE TITLE
Show some text in Supermon and Supermon2 indicating that SkywarnPlus is either enabled or disabled 

### ISSUE THREAD

**Issue by scseifert** [Mason10198/SkywarnPlus#122]
**Is your feature request related to a problem? Please describe.**
Out in the field, unless there is an alert we don't know if SWP is enabled or disabled without toggling it on and off with DTMF which interrupts communications.  

**Describe the solution you'd like**
We could see SWP's status via Supermon or Supermon2

**Describe alternatives you've considered**
I can't think of any others
**Additional context**

**Comment by Mason10198** [comment]
Hi, this feature was added back in July with v0.8.0. Please read here: https://github.com/Mason10198/SkywarnPlus/releases/tag/v0.8.0
