### ISSUE TITLE
Full WX detail readout for Severe Alerts

### ISSUE THREAD

**Issue by Mason10198** [Mason10198/SkywarnPlus#14]
### Discussed in https://github.com/Mason10198/SkywarnPlus/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **AI7NC** June 15, 2023</sup>
Mason and I already talked about this idea a little bit, but I wanted to get it in the discussion list. 

Provide ability to either via a macro or automatically for severe WX alerts generate a wav file with the full details of the WX alert text rather than just the type.

For my repeater it would be nice to have this automatic when a Severe alert is issued.

Nathan, AI7NC </div>

**Comment by k5dvt** [comment]
I second the motion that it needs to be via a macro or at least to turn on and off. It may get in the way of an actual skywarn net.

**Comment by Mason10198** [comment]
Implemented in `v0.2.3`
