### ISSUE TITLE
Manually Reset CTs

### ISSUE THREAD

**Issue by k5dvt** [Mason10198/SkywarnPlus#15]
It would be nice to have a command that brute forces the tones to revert back to their default, just for testing and while setting up tones to try them out to see which they like. I know it's like two commands of renaming but still I'm lazy.

Also might not be a bad idea to include all those CTs I sent you with the package just so folks have a variety of the defaults to choose from.

**Comment by Mason10198** [comment]
Implemented in [v0.2.0](https://github.com/Mason10198/SkywarnPlus/releases/tag/v0.2.0)
