### ISSUE TITLE
Auto Start at boot?

### ISSUE THREAD

**Issue by captdonm** [Mason10198/SkywarnPlus#19]
I don't leave my node on all the time. Is there an auto start SkywarnPlus on Boot? 
Thanks!

**Comment by Mason10198** [comment]
`SkywarnPlus` does not really "start". Instead, it is executed at a set interval. Every time it is executed, it downloads new weather information and performs tasks based on any alerts that it detects. Looking at the [installation instructions](https://github.com/Mason10198/SkywarnPlus#installation), you will see the section about adding an entry in your `crontab` that will automatically execute `SkywarnPlus` every 60 seconds. This `crontab` entry will be effective any time the node is powered on, so you don't have to worry about reboots.

> 5. **Crontab Entry**
> 
>    Add a crontab entry to call SkywarnPlus on an interval. Open your crontab file using the `crontab -e` command, and add the following line:
>
>   ```bash
>   * * * * * /usr/local/bin/SkywarnPlus/SkywarnPlus.py
>   ```
>
>   This command will execute SkywarnPlus (poll NWS API for data) every minute.

**Comment by captdonm** [comment]
Thanks! I was using Autosky before I installed this and everytime I started up my node it said autosky enabled. I did add that to my crontab already so I should be good to go. now to wait for a weather alert!
