### ISSUE TITLE
Update leaves issues in config.yaml

### ISSUE THREAD

**Issue by w4edp** [Mason10198/SkywarnPlus#41]
Have tried the new Update, and it's causing a few issues.  I have attached  before and after config.yaml files from UpdateSWP.py was run, below are some issues I'm seeing.  Some things seem to be just "jumbled out of place".

I've tried to make very sure it isn't me by doing a brand new install and left the config completely "stock" except for items that were enabled, etc.

- If max alerts is enabled, after Update it is commented out and set back to default
- Alert suffix is removed and commented out
- TailMessage Suffix is removed and commented out
- TailMessage Path is removed and commented out
- LogPath is removed and commented out

I removed my API and User keys, other than that the before and after files have not been changed.

Thanks for looking!

[before_and_after.config.yaml.tar.gz](https://github.com/Mason10198/SkywarnPlus/files/12002406/before_and_after.config.yaml.tar.gz)

**Comment by w4edp** [comment]
After doing a comprehensive review of the before and after, it seems the 5 items I mention are indeed there, however... The items are defaulted in their respective "section" of the config file and have been inserted below their respective "section" in the config file.

So all is technically correct, it's just out of place and not where it is expected to be.

I'll leave this issue active so that you can see what I'm seeing.

Thanks again for all your work!

**Comment by Mason10198** [comment]
Please try the new `v0.3.3` and see if the update script correctly handles your configuration. I have reformatted `config.yaml` so that it no longer uses commented-out values. Make sure you replace the Update script with the latest version as described in the release.

**Comment by Mason10198** [comment]
Also, please run through some test scenarios using the INJECTALERTS feature or by using a county code with active alerts to ensure all SkywarnPlus functions still operate correctly after the `v0.3.3` update and new `config.yaml` format.

**Comment by w4edp** [comment]
Update worked perfectly, Thanks!

Functions I have tested seem to be working as expected.

**Comment by w4edp** [comment]
Is the AlertSuffix supposed to go out following the All Clear message?  Could it be set to?

**Comment by Mason10198** [comment]
No, AlertSuffix is only appended to the SayAlert message. I could have added a "SayAllClearSuffix", but since the AllClear message is always the same, this functionality would be no different than if you were to simply manually edit the AllClear WAV to append some sound to the end of it. You would probably need to edit the WAV to cut off the "for this area" at the end anyways, if you were wanting to add a suffix.

If you find your problems resolved please close this issue. Thank you!

**Comment by w4edp** [comment]
Please consider an option to have the ability to add a Suffix to the All Clear message.  My repeaters cover 3 states and multiple counties in each.  No matter how I edit the AllClear audio file, it will not let people know a county/state that is aligned with the alert.
