### ISSUE TITLE
New Install of ASL "Beta" version & SkywarnPlus

### ISSUE THREAD

**Issue by wrhowell** [Mason10198/SkywarnPlus#43]
Machine:        Wyse 5020 Machine, 1TB SSD & 16gig memory
OS:                Ubuntu 20.04 Destop with Virtualbox Install
VM Running: ASL "Beta" Version: AllStarLink ASL 2.0.0-beta (http://downloads.allstarlink.org/index.php?b=ASL_Images_Beta)

When running "./SkywarnPlus.py" it returns the following:

Traceback (most recent call last):
     File "./SkywarnPlus.py", line 43, in <module>
           from dateutil import parser
ImportError: No module named 'dateutil'

Suggested repair procedures, please?

**Comment by Mason10198** [comment]
The error message you provided explains the issue. You have not properly installed the required dependency packages as per the installation instructions:

> Follow the steps below to install:
> 
> 1. **Dependencies**
> 
>    Install the required dependencies using the following commands:
> 
>    **Debian**
> 
>    ```bash
>    apt install unzip python3 python3-pip ffmpeg
>    pip3 install ruamel.yaml requests python-dateutil pydub
>    ```

**Comment by wrhowell** [comment]
Actually, I thought that were the problem and went back (twice) and ran those commands again with still the same results.

So I will do a complete remove/install of ASL then install the SkywarPlus again and see what happens.

**Comment by Mason10198** [comment]
Please make sure you update ASL with `apt update` and `apt upgrade` after installing ASL to ensure Python and Pip are up to date. The current versions of the ASL beta image are very out of date and you will likely encounter PUBKEY errors on the ASL repo when running `apt update`. Solution for this is readily available with a Google search.

Install the dependencies line-by-line, and check for errors in the output between each command. Post any errors you find here.

**Comment by wrhowell** [comment]
Ok sir, I've cleaned the drive (started with a whole new VM, installed the ASL Beta, then followed your command on installing SkywarnPlus now for the third time.
Thinking that I being 73 goofed something up and each time I run "./SkywarnPlus.py I still get the same thing....

See attached pic...

**Comment by wrhowell** [comment]
I forgot to add, t\each time of the three times I did a apt update then a apt upgrade just to make sure everything was as close to current as possible.

**Comment by Mason10198** [comment]
Images cannot be uploaded to Github via email. You must log in to Github and post the image directly to the issue thread. Thank you

**Comment by wrhowell** [comment]
Well, I will try to do that... in the mean time, I have it working on a Pi, the only thing is ---
I've had like three people already this morning tell me to turn it off. That screeching alert sound (as they call it) needs to be changed to something else. People saying it sounds like a whistle on a steam ship and hurts their ears, so do you have another sound in your sound files that is closer to what the weather service uses on their weather monitors by chance, or something of a lower tone alert sound that you would recommend?

**Comment by Mason10198** [comment]
The purpose of the alert sound is to get your attention. If you don't like it, you can change it. The project is open source and I have already extensively documented and structured the files and explained how to change them if you desire.

**Comment by wrhowell** [comment]
I understand that, I know how to change them, was just asking if you had some other "recommended" tones that are closer too what NWS uses since you designed this and know what all tones you have placed in your sounds files.

Thanks anyways.

**Comment by Mason10198** [comment]
The only alternative tones included are intended to be used as courtesy tones.

I have no recommendations other than to use the included file, which is why it is included.

I'm not sure what you mean by "what the NWS uses", unless you are talking about EAS/SAME tones, which are not auditory alerts but instead digital data packets containing alert information.

Back on the original subject of this issue, please provide more information about your installation errors. Based on the original error you provided, your node simply does not have the "python-dateutil" Python package installed, which indicates that you either encountered errors while installing the prerequisite packages without realizing, or did not follow the instructions correctly. Both cases would not be an "issue" of SkywarnPlus and technically do not need to be posted here, but I am still willing to assist.

**Comment by Mason10198** [comment]
I re-created your setup with a fresh VirtualBox VM of `asl-2.0.0-beta.6` and was unable to replicate your issue, or any issues for that matter, following the instructions in the `README.md`. I will continue to assume that the issue you are encountering has no relevance to SkywarnPlus directly, and will be closing this issue as completed soon unless proven otherwise.

Additional notes:
I just released `v0.3.5` which makes it even easier to customize the audio files and sound effects, without needing to cut/splice them in software.

**Comment by wrhowell** [comment]
Thank you, I will try out the new version early next week.

**Comment by wrhowell** [comment]
Ok, I went and wiped the drive clean, install ASL (non beta version) from start to finish, did `sudo apt update`, then `sudo apt upgrade`, then did the `sudo apt install unzip python3 python3-pip ffmpeg`, then did the `sudo pip3 install ruamel.yaml request python-dateutil pydub`, then did the github thing, then unzipped the file, then `rm` the zip file, then the `chmod` thing, then went thru the yaml config and set all that up, made the modes within rpt as stated, and have gotten to the point of  running `sudo /usr/local/bin/SkywarnPlus/SkyControl.py` ---- and am gettin the following in return --- "

```
Traceback (most recent call last):
     File "/usr/local/bin/SkywarnPlus/SkyControl.py", line 30, in <module>
        from ruamel.yaml import YAML
ImportError: No module named 'ruamel'
```

Suggestions/recommends?

**Comment by mjwgeek** [comment]
when you run 
pip3 install ruamel.yaml
what happens?

on a brand new system,  this is what I got:

pip3 install ruamel.yaml
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting ruamel.yaml
  Downloading https://www.piwheels.org/simple/ruamel-yaml/ruamel.yaml-0.17.32-py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 289 kB/s
Collecting ruamel.yaml.clib>=0.2.7
  Downloading ruamel.yaml.clib-0.2.7-cp39-cp39-manylinux2014_aarch64.whl (651 kB)
     |████████████████████████████████| 651 kB 2.8 MB/s
Installing collected packages: ruamel.yaml.clib, ruamel.yaml
Successfully installed ruamel.yaml-0.17.32 ruamel.yaml.clib-0.2.7

**Comment by wrhowell** [comment]
At first since I was using sudo comman it thru an error that the '/home/william/.cache/pip/http' or its parent directory is not owned by the current user and to use the -H with sudo which I did...

then got this:

Downloading https://files.pythonhosted.org/packages/d9/0e/(key info stuff too long to enter)/ruamel.yaml-0.17.32-py3-none-any.whl (112kb)
               100% |                                                        | 112kb 959kb/s
collecting request
        Could not find a version that satisfies the requirement request (from version:)
No matching distribution found for request
You are using pip version 8.1.1, however version 23.2.1 is avaiable.
You should consider upgrading via the 'pip install --upgrade pip' command.

I do believe that per the utube video that the warning is normal ---- am I wrong?

William

**Comment by mjwgeek** [comment]
I haven't personally used the non beta ASL in years to be honest. if sudo /usr/local/bin/SkywarnPlus/SkyControl.py still doesn't work then I would upgrade as it stated.

**Comment by wrhowell** [comment]
I can try that and see what happens I guess.... can't hurt anything I don't imagine. Worse that could happen is having to do a rm/install of a new VM...

William
