### ISSUE TITLE
won't run on ASL Beta 2.0.0

### ISSUE THREAD

**Issue by rlmurray56** [Mason10198/SkywarnPlus#53]
**Describe the bug**
Traceback (most recent call last):
  File "/usr/local/bin/SkywarnPlus/SkywarnPlus.py", line 45, in <module>
    from dateutil import parser
ModuleNotFoundError: No module named 'dateutil'

**To Reproduce**
Up to date Debian 10 "buster" system, ASL 2.0.0 beta, followed your GitHub install instructions for dependencies, installed SkywarnPlus, but error message above when attempting to start the program

**Comment by Mason10198** [comment]
Please run `pip3 install python-dateutil` and copy/paste the exact output that results from this command.

**Comment by rlmurray56** [comment]
Please close this. Not a bug, operator error. Resolved by updating gpg key.
