### ISSUE TITLE
Red Flag Warnings - Note about fire zones - not a request

### ISSUE THREAD

**Issue by nathantcampbell** [Mason10198/SkywarnPlus#59]
Our area has officially entered a red flag warning for fire weather. I was perplexed at first as to why they weren't showing up in the API pull for the NOAA WX zones but did at the county level. Because our county covers both the cascades and the coast range, I didn't want a county wide API pull on my repeater as it only covers the cascade range.

Come to find out there are completely separate fire weather zones, after adding those to the list I was correctly getting the red flag warning. You can find the fire zone maps here: https://www.weather.gov/pimar/FireZones The API code uses the same prefix as your WX zones. So for Oregon fire zone 608, the api code is 'ORZ608'.

No feature request other than maybe adding something about fire weather zones to the documents, I'm just dropping this in here for folks that are in fire prone areas that don't want to list a full county in their alerting zones.

Nathan, AI7NC

**Comment by tsawyer** [comment]
There is mention of zones, including fire zones in the README.

**Comment by Mason10198** [comment]
Quote from `README.md`:

>    ## **IMPORTANT**: YOU WILL MISS ALERTS IF YOU USE A **ZONE** CODE. DO NOT USE **ZONE** CODES UNLESS YOU KNOW WHAT YOU ARE DOING.
> 
>    According to the official [NWS API documentation](https://www.weather.gov/documentation/services-web-api):
> 
>    > "For large scale or longer lasting events, such as snow storms, fire threat, or heat events, alerts are issued
>    > by NWS public forecast zones or fire weather zones. These zones differ in size and can cross county
>    > boundaries."
> 
>    > "...county based alerts are not mapped to zones but zone based alerts are mapped to counties."
> 
>    This means that if you use a County code, you will receive all alerts for both your County **AND** your Zone - but if you use a Zone code, you will **ONLY** receive alerts that cover the entire Zone, and none of the alerts specific to your County.

I think this covers it, unless I missed something in my initial research. The `ORZ608` code you are using is not special, it is just a "zone" code instead of a "county" code as mentioned here. [You can see all zone and county codes here.](https://alerts.weather.gov/) Do you suggest any changes to the documentation?

**Comment by nathantcampbell** [comment]
ORZ606 and ORZ608 are *fireweather zones *per the fire weather map:
https://www.weather.gov/media/pimar/FireZone/or_firezone.pdf
For WX alerts I had been using the *WX zones* ORZ012 and ORZ013. If you
pull these up you'll see they overlap with the firezones but have way
different boundaries. If I use my county code ORC039, I do get the
appropriate red flag alert, but because of the size of our county vs
coverage of my repeater I don't use the county code.

In the notes I'd recommend adding the below link to the firezones as
they're not included or mentioned in the current included link to the wx /
county zones. Redflag alerts will only show up under the firezones and
county, and won't show in the WX zones.
https://www.weather.gov/pimar/FireZones

Nathan Campbell

**Comment by tsawyer** [comment]
Would those Fireweather Zones be added like so?
```
Alerting:
  #   CAC059 is Orange County Alerts
  #   CAC257 is Santa Ana Mountians Fire Warnings
  #   CAC552 is Orange County Costal Fire Warings
  #   CAC554 is Orange County Inland Fire Warnings
  CountyCodes:
    - CAC059
    - CAC257
    - CAC552
    - CAT554
```

Edit: I found these in the Zone list. So can I do?
```
 Alerting:
  CountyCodes:
    - CAC059
    - CAZ257
    - CAZ552
    - CAZ554
```

**Comment by nathantcampbell** [comment]
Yes you add them just as if they're county codes or whether zone codes.

Nathan
