### ISSUE TITLE
Not playing active warning - error in log file

### ISSUE THREAD

**Issue by Steve-AG2AA** [Mason10198/SkywarnPlus#79]
I added NYC023 because it had an active warning so I could test. No tail message played, no red message on supermon. when county NYC023 is not in the list, no error generated in log. 

llinux log:
Feb 10 13:55:04 HamVoIP_Radioless2 CROND[1858]: (root) CMDOUT (Traceback (most recent call last):)
Feb 10 13:55:04 HamVoIP_Radioless2 CROND[1858]: (root) CMDOUT (  File "/usr/local/bin/SkywarnPlus/SkywarnPlus.py", line 1805, in )
Feb 10 13:55:04 HamVoIP_Radioless2 CROND[1858]: (root) CMDOUT (    main())
Feb 10 13:55:04 HamVoIP_Radioless2 CROND[1858]: (root) CMDOUT (  File "/usr/local/bin/SkywarnPlus/SkywarnPlus.py", line 1581, in main)
Feb 10 13:55:04 HamVoIP_Radioless2 CROND[1858]: (root) CMDOUT (    alerts = get_alerts(COUNTY_CODES))
Feb 10 13:55:04 HamVoIP_Radioless2 CROND[1858]: (root) CMDOUT (  File "/usr/local/bin/SkywarnPlus/SkywarnPlus.py", line 527, in get_alerts)
Feb 10 13:55:04 HamVoIP_Radioless2 CROND[1858]: (root) CMDOUT (    start_time = parser.isoparse(start))
Feb 10 13:55:04 HamVoIP_Radioless2 CROND[1858]: (root) CMDOUT (AttributeError: 'ArgumentParser' object has no attribute 'isoparse')

config.yaml

[root@HamVoIP_Radioless2 SkywarnPlus]# nano config.yaml
  GNU nano 2.5.3             File: config.yaml

  #   - ARC119: "Pulaski.wav"
  CountyCodes:
  - NYZ010
  - NYC029
  - NYC063
  - NYC023

  # Enable instant voice announcement when new weather alerts are issued.
  SayAlert: true

  # Enable SayAlert to "say" any alerts whose list of affected counties has cha$
  # Only applies if more than one CountyCode is specified AND County IDs have b$
  SayAlertsChanged: true

  # When a change is detected, make SayAlert say ALL of the currently active al$
  SayAlertAll: false

  # Specify the WAV file in the SOUNDS/ALERTS directory to use as the alert sou$
  AlertSound: Duncecap.wav

**Comment by Mason10198** [comment]
Please update to the latest version (v0.6.1) to resolve this issue.

**Comment by Steve-AG2AA** [comment]
thank you for putting the update script in the skywarn plus directory as the regular hamvoip update (menu option one) does not update skywarn plus. skywarn plus now operating as expected with test county. thank you.
