### ISSUE TITLE
Ablity to change Repeater ID

### ISSUE THREAD

**Issue by k5dvt** [Mason10198/SkywarnPlus#8]
Let me explain with an example:

It would be nice to have SkywarnPlus switch my normal ID of the voice "W - X - 5 - N - A - S" to a shorted K5DVT in CW at 20WPM. The idea here is to shorten up the time needed to ID to "get out of the way" of traffic on the radio, since most hams instinctively wait for the IDer to go buy and not just talk on top of it. The CW ID could be sent and gone by the time the voice ID gets to announcing the 5.

**Comment by Mason10198** [comment]
Implemented in [v0.2.0](https://github.com/Mason10198/SkywarnPlus/releases/tag/v0.2.0)
