### ISSUE TITLE
Noisy/corrupt  tail message created

### ISSUE THREAD

**Issue by blu666z** [Mason10198/SkywarnPlus#81]
I have two nodes which have created a very noisy/corrupt tail message for a Winter Storm Warning which is active for my county.  Two days again, I had tail messages created correctly for a Dense Fog Advisory, so I believe my installation is correct.  I was not monitoring the node when the initial Broadcast was played to know if that sounded correct.

This is an installation on a HamVoip node.

I have attached my config file, current data.json, and created wx-tail.ulaw.

Thanks for any guidance.

-Kevin (KE7K)

[wx-tail.zip](https://github.com/Mason10198/SkywarnPlus/files/14283763/wx-tail.zip)

**Comment by Mason10198** [comment]
It looks like you changed the tailmessage file extension to `.ulaw` in your `config.yaml`, which is causing the issue.

Please change:
```yaml
  # Specify an alternative path and filename for saving the tail message.
  # Default is /tmp/SkywarnPlus/wx-tail.wav.
  TailmessagePath: /tmp/SkywarnPlus/wx-tail.ulaw
```
Back to:
```yaml
  # Specify an alternative path and filename for saving the tail message.
  # Default is /tmp/SkywarnPlus/wx-tail.wav.
  TailmessagePath: /tmp/SkywarnPlus/wx-tail.wav
```
and also make the change in your `rpt.conf`.

**Comment by blu666z** [comment]
I was having an issue with the tail message not playing at all when it was .wav and was told by K4FXC, the curator of HamVoip, that the tail message code would not handle .wav files and it needed to be ulaw. 

"The tailmessage code won't play a .wav file.  It must be converted to one
of the raw/binary formats.  For example, I use ulaw files. To convert a
.wav to .ul:"


I'll play around with it some more.  Thanks for your quick response. 

-Kevin

**Comment by Mason10198** [comment]
That is not correct at all. Asterisk/app_rpt perfectly handles the `.wav` files created by SWP on all distributions, HamVoIP included. There are many HamVoIP systems currently running SkywarnPlus with tailmessages enabled.

Even if the file did need to be converted, you cannot simply change the extension in the configuration file, as that will only change the file name and not the actual encoding of the data in the file, which would require changing the SkywarnPlus source code.

**Comment by blu666z** [comment]
Understood.  Thanks again Mason.   Feel free to close this.

**Comment by Mason10198** [comment]
No worries. If you still have issues with the `.wav` file playing, try playing the file manually from the Asterisk console (`asterisk -rvvv`) and watch for errors. Come back here if you need help.
