### ISSUE TITLE
no silence is inserted between the all clear message and suffix

### ISSUE THREAD

**Issue by Mason10198** [Mason10198/SkywarnPlus#86]
Okay one minor note after more testing; 600ms of silence is inserted between the alert message and the suffix, but no silence is inserted between the all clear message and suffix. Is this intentional?

_Originally posted by @ad6g in https://github.com/Mason10198/SkywarnPlus/discussions/84#discussioncomment-8814803_

**Comment by Mason10198** [comment]
Resolved in `v0.6.2`

**Comment by ad6g** [comment]
Appears to be working fine. Thanks again for the quick work.
