### ISSUE TITLE
Ablity to run macros on a given alert

### ISSUE THREAD

**Issue by k5dvt** [Mason10198/SkywarnPlus#9]
I would like to be able to run macros (set GPIO pins high/low, run DTMF commands/macros) for a given weather condition. The purpose of this is to say, automatically link to another Skywarn system when there are weather advisories or higher.

**Comment by Mason10198** [comment]
Implemented in [v0.2.0](https://github.com/Mason10198/SkywarnPlus/releases/tag/v0.2.0)
